settings:
  tls_ca_root_file: "/config/root.ca.crt"
scenario1:
  # token that has file 
  token:
  # File ID EGAF stableId
  file_id: "EGAF000000001"
  # if the scenario calls for downloading an encrypted file
  encrypted:
    # Encryption format can be aes, crypt4gh
    format: "aes"
    destination_key: ""
    destination_iv: ""
scenario2:
  # token that has file 
  token:
  # File ID EGAF stableId
  file_id: "EGAF000000001"
scenario3:
  # token that has files
  token:
  # File ID EGAF stableId
  file_1_id: "EGAF000000001"
  file_2_id: "EGAF000000002"
  file_3_id: "EGAF000000003"
  file_4_id: "EGAF000000004"
  file_5_id: "EGAF000000005"
scenario4:
  # token that has file_1
  token_1:
  # token that has file_1
  token_2:
  # File ID EGAF stableId
  file_1_id: "EGAF000000001"
  file_2_id: "EGAF000000002"
scenario5:
  # token that has file 
  token:
  # File ID EGAF stableId
  file_id: "EGAF000000001"
  encrypted:
    # Encryption format can be aes, crypt4gh
    format: "aes"
    destination_key: ""
    destination_iv: ""

