settings:
  # Username to identify the user in CentralEGA
  user: "dummy"
  # User secret private RSA key.
  user_key: "~/tests/_common/dummy.sec"
scenario1:
  # Path to test file needs to be crypt4gh format
  test_file: "test_file.txt"
scenario2:
  # Path to test file needs to be crypt4gh format
  test_file: "test_file.txt"
  # New file name on remote
  new_file: "new_name.c4ga"
scenario3:
  # Path to test file needs to be crypt4gh format
  test_file: "test_file.txt"
  # New file name on remote
  new_file: "new_name.c4ga"
scenario4:
  # Path to test file needs to be crypt4gh format
  test_file: "test_file.txt"
  # New file name on remote
  new_file: "new_name.c4ga"
scenario5:
  # Path to test file needs to be crypt4gh format
  test_file: "test_file.txt"
  # New file name on remote
  new_file: "new_name.c4ga"
